### ISSUE TITLE
Incompatibility of the website on Apple devices

### ISSUE THREAD

**Issue by Krishna14** [WeibelLab-Teaching/CSE_218_118_Fa20_Team_Immersive_Truth#1]
@Gabriel Beal, could you please update the status of your discussion with the professor regarding the issue of "website not rendering movements made without touch in Apple devices"?

**Comment by Yaffoman** [comment]
Spoke with another student about the issue. Solution involved using VR rather than XR. Need to still investigate implications of this change, however I have implemented it and it works
